encrypt-type: # 0：普通， 1：国密
  encrypt-type: 0

group-channel-connections-config:
  all-channel-connections:
    - group-id: 1  # 群组ID
      connections-str:
        - 127.0.0.1:20200  # 节点，listen_ip:channel_listen_port
        - 127.0.0.1:20201
    - group-id: 2
      connections-str:
        - 127.0.0.1:20202  # 节点，listen_ip:channel_listen_port
        - 127.0.0.1:20203

channel-service:
  group-id: 1 # sdk实际连接的群组
  agency-name: fisco # 机构名称

spring:
  datasource:
    username: root
    password: hexianbo
    url: jdbc:mysql://localhost/demo?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity